project_id = "executa-ai"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions", "app"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
