// Generated by scripts/generate-blog-content.mjs. Do not edit manually.
import type { BlogPost } from "./types";

export const generatedBlogPosts: BlogPost[] = [
  {
    "slug": "homologacao-do-qr-semantico-p0",
    "title": "Homologação do QR semântico P0",
    "excerpt": "Publicação operacional para validar ponta a ponta a emissão, impressão e resolução dos quatro QR semânticos do EXECUTA.AI.",
    "category": "Produto",
    "publishedAt": "2026-07-28",
    "readingMinutes": 1,
    "featured": false,
    "coverPattern": "steps",
    "coverLabel": "PREVIEW / PUB-20260728-b4fbb3cc",
    "sections": [
      {
        "heading": "Introdução",
        "paragraphs": [
          "Esta publicação registra a primeira homologação operacional do roteador de QR semântico do EXECUTA.AI. Os códigos impressos usam tokens opacos e estáveis, sem incorporar URLs temporárias de fornecedores."
        ]
      },
      {
        "heading": "O que será validado",
        "paragraphs": [
          "Serão verificados os quatro destinos: criar contexto editorial, abrir o Preview correspondente, iniciar o contexto de aprovação sem executar ações silenciosas e consultar a trilha de medição."
        ]
      },
      {
        "heading": "Como realizar o teste",
        "paragraphs": [
          "Abra a câmera do celular, leia cada QR e confirme se o título e a ação exibidos correspondem à legenda impressa. Registre qualquer falha de leitura, redirecionamento ou legibilidade como evidência da etapa E5."
        ]
      },
      {
        "heading": "Critério de aceite",
        "paragraphs": [
          "O teste é aprovado quando os quatro códigos são reconhecidos no celular, direcionam para o contexto correto e permanecem legíveis após impressão em A4 a 100% de escala."
        ]
      }
    ]
  }
];
